services:
  - type: web
    name: feature-selector-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn feature_selector.wsgi:application
    plan: free
    autoDeploy: true
