# Generated by Django 5.2.7 on 2025-10-30 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garesult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
