# Generated by Django 5.2.7 on 2025-10-30 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_garesult_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('method_name', models.CharField(max_length=100)),
                ('selected_features', models.TextField()),
                ('accuracy', models.FloatField()),
                ('execution_time', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='garesult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
